#  MODS  #
$terminal = kitty
$menu = wofi --show drun
$browser = zen
$volumeControl = pavucontrol
$mainMod = SUPER


# INCLUDES  #
source = ~/.config/hypr/includes/enviroments.conf
source = ~/.config/hypr/includes/autostart.conf
source = ~/.config/hypr/includes/monitors.conf
source = ~/.config/hypr/includes/input.conf
source = ~/.config/hypr/includes/binds.conf
source = ~/.config/hypr/includes/looknfeel.conf
source = ~/.config/hypr/includes/rules.conf
