#  KEYBINDS  #
bind = $mainMod, Q, exec, kitty
bind = $mainMod, W, killactive
bind = $mainMod, E, exec, thunar
bind = $mainMod, R, exec, wofi

bind = $mainMod, F, fullscreen
bind = $mainMod, V, togglefloating
bind = $mainMod, Escape, exec, pkill waybar || waybar
bind = $mainMod, Print, exec, grim - | wl-copy
bind = , Print, exec, sh -c "slurp | grim -g - - | wl-copy"

bind = $mainMod, B, exec, zen-browser
bind = $mainMod, O, exec, obsidian
bind = $mainMod, G, exec, steam
bind = $mainMod, Z, exec, pavucontrol

# Move focus with mainMod + arrow keys
bind = $mainMod, h, movefocus, l
bind = $mainMod, j, movefocus, d
bind = $mainMod, k, movefocus, u
bind = $mainMod, l, movefocus, r

# Move focused window
bind = $mainMod SHIFT, h, movewindow, l
bind = $mainMod SHIFT, j, movewindow, d
bind = $mainMod SHIFT, k, movewindow, u
bind = $mainMod SHIFT, l, movewindow, r

# Resize focused window
bind = $mainMod CTRL, h, resizeactive, -50 0
bind = $mainMod CTRL, j, resizeactive, 0 50
bind = $mainMod CTRL, k, resizeactive, 0 -50
bind = $mainMod CTRL, l, resizeactive, 50 0

# Switch workspaces
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4

# Move active window to a workspace
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4

# Move/resize windows with mouse
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
