; COLORS
[colors]
background = #282828
background-alt = #3c3836
foreground = #ebdbb2
foreground-alt = #928374

green = #98971a
yellow = #fabd2f
blue = #458588
red = #cc241d
aqua = #83a598
purple = #b16286
orange = #d79921

; BAR
[bar/main]
width = 100%
height = 30
offset-x = 0
offset-y = 0
radius = 0
fixed-center = true

background = ${colors.background}
foreground = ${colors.foreground}

font-0 = JetBrainsMono:size=10;3

module-margin-left = 2
module-margin-right = 2
separator = 

modules-left = xworkspaces
modules-center = date
modules-right = custom/power

[settings]
screenchange-reload = true
pseudo-transparency = true

; WORKSPACES
[module/xworkspaces]
type = internal/xworkspaces
label-active = %name%
label-active-background = ${colors.green}
label-active-foreground = ${colors.background}
label-active-padding = 3

label-inactive = %name%
label-inactive-foreground = ${colors.foreground-alt}
label-inactive-padding = 3

label-urgent = %name%
label-urgent-foreground = ${colors.red}
label-urgent-padding = 3

label-occupied = %name%
label-occupied-foreground = ${colors.foreground}
label-occupied-padding = 3

label-empty = %name%
label-empty-foreground = ${colors.foreground-alt}
label-empty-padding = 3

; CLOCK
[module/date]
type = internal/date
interval = 5
date = %H:%M
date-alt = %d/%m
label = %date%
label-foreground = ${colors.yellow}
label-font = 0

; CPU
[module/cpu]
type = internal/cpu
interval = 0.5
format = <label>
label = %percentage%% 
label-foreground = ${colors.aqua}

; MEMORY
[module/memory]
type = internal/memory
interval = 0.5
format = <label>
label = %percentage_used%% 
label-foreground = ${colors.purple}

; AUDIO
[module/pulseaudio]
type = internal/pulseaudio
interval = 1
format-volume = <label-volume> <ramp-volume>
format-volume-foreground = ${colors.orange}
format-muted = 0% 
format-muted-foreground = ${colors.red}
label-volume = %percentage%%
label-volume-padding = 0 10 0 10

ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 

; BATTERY
[module/battery]
type = internal/battery
poll-interval = 0.5
battery = BAT0
adapter = ADP1
full-at = 98
low-at = 20

format-charging = <label-charging>
label-charging = %percentage%% 
label-charging-foreground = ${colors.green}

format-discharging = <ramp-capacity> <label-discharging>
label-discharging = %percentage%%
label-discharging-foreground = ${colors.foreground}

format-full = <label-full>
label-full = %percentage%% 
label-full-foreground = ${colors.green}

format-plugged = <label-plugged>
label-plugged = %percentage%% 
label-plugged-foreground = ${colors.foreground}

format-low = <label-low>
label-low = %percentage%% 
label-low-foreground = ${colors.red}

ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 

; POWER
[module/custom/power]
type = custom/script
exec = echo " ⏻ "
interval = never
format = <label>
label = ⏻
label-foreground = ${colors.red}
click-left = i3-msg exit
format-padding = 4
