# Imagens
mime ^image, has eog, X, flag f = eog "$@"

# Vídeo e áudio
mime ^video, has mpv, X, flag f = mpv "$@"
mime ^audio, has mpv, X, flag f = mpv "$@"

# Zip
ext zip, has unzip = unzip "$1" -d "$1%"

# Código e texto
ext md|txt|log|conf|toml|yaml|yml|json|sh|lua|py|rs|go|js|ts|tsx|jsx|html|css = nvim "$@"
mime ^text = nvim "$@"
